### ISSUE TITLE
Definições página Home

### ISSUE THREAD

**Issue by felipekm** [plingbr/pling.net.br#1]
# Descrição
- Landing page semelhante as páginas de Mercado, com os menus no topo com logo e navegação vertical.

- Suprimir botão login, contratar;
- Itens do menu: Quem somos, Compromisso social, Trabalhe conosco;
- Ícones Twitter e Facebook alinhados à esquerda;

## Primeira seção: Home
- Titulo: TBD
- Descrição: TBD
- Imagem de fundo: http://sbmicrobiologia.org.br/wp-content/uploads/2015/11/marte_0.jpg;
- Voltar para esta sessão ao clicar no logo da Pling, como já é

## Segunda seção: Compromisso social
- Parágrafo:
> Nós apoiamos o Médico Sem Fronteiras e incentivamos que você também apoie
- Dois botões: Doe agora, Saiba mais;
- Texto e botões centralizados conforme imagem:
![image](https://cloud.githubusercontent.com/assets/205932/24419611/17b7a7c6-13c6-11e7-88e9-a3837110a811.png)

## Terça seção: Trabalhe conosco
- Frase:TBD
- Imagem de fundo: TBD
- Botão: Saiba mais

**Comment by ezequielmross** [comment]
TDT: 1dia 4 hs (mais demorado pois comecei de um jeito e acabei alterando depois)
