### ISSUE TITLE
Inclusão de Tags para prover o "Analytics"

### ISSUE THREAD

**Issue by tanisesarmento** [plingbr/pling.net.br#12]
Incluir as seguinte tags no http://pling.net.br

Copy the code below and paste it onto every page of your website.
Paste this code as high in the <head> of the page as possible:

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WCSMMFG');</script>

Additionally, paste this code immediately after the opening <body> tag:

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WCSMMFG"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

Em caso de dúvidas, trocar uma ideia com @felipekm

**Comment by FabioFerreiraIT** [comment]
TDT: 0,5h
Por não conter o fluxo de HML, foi aplicado na master e já refledito em Produção. 
Validação realizado em ambos ambientes.
