### ISSUE TITLE
www.pling.net.br/compromisso_social

### ISSUE THREAD

**Issue by felipekm** [plingbr/pling.net.br#2]
# Descrição

URL da página: https://www.pling.net.br/compromisso-social**
- Será acionada através de vários canais diferentes, como por exemplo o botão saiba mais da tela de login.

- Será umá singlepage contendo 4 menus/seções.
- Podemos usar exatamente a mesma estrutura que fizemos para os sites de marca. Inclusive com aquela ideia da barra se fixar na medida em que navega. 

## **Primeira seção - Compromisso social**
- Titulo Compromisso Social
- Logo da PLING centralizada, uma imagem de fundo (a mesma que estivermos usando na tela de login)  com uma camada de transparência e a frase em branco: 
  > Nós realmente acreditamos que podemos contribuir para um mundo melhor.  Um pouco pela nossa própria contribuição mensal, um pouco pela contribuição de nossos clientes e, principalmente, pelo exemplo que podemos dar para que outras empresas façam o mesmo. E também acreditamos que o Médico Sem Fronteiras é o destino ideal de nossos esforços.

## **Segunda  seção - Fatos**
- Título:
  > 10 fatos relevantes em relação ao nosso compromisso social.

- Dividir esta seção em dois pedaços. 5 fatos relevantes de cada lado. Cada fato relevante tem um título e um parágrafo de texto. Tipo imagem abaixo:
![image](https://cloud.githubusercontent.com/assets/16900593/23949661/ebc07710-0966-11e7-87b7-8d7c396d7d2e.png)

## **Terceira seção - Como funciona**
- Título: Como funciona?
> Quando nossos clientes contratam algum de nossos serviços, eles podem optar por doar até 3% do valor bruto do contrato para o MSF. Nós, da PLING, doamos o mesmo valor do cliente, independente da nossa doação mensal fixa. 

## **Quarta  seção - Doações**
- Título:  Acompanhe nossas doações.

**Comment by ezequielmross** [comment]
TDT: 3 hs
