### ISSUE TITLE
Conteúdo do site e oturas coisas

### ISSUE THREAD

**Issue by pauloesteves** [plingbr/pling.net.br#6]
- [ ] 1. Menus serão, nesta ordem : Início, Perfil, Compromisso Social, Trabalhe conosco e Contato. 

- [ ] 2. Fazer a home ser idêntica à seção Quem somos dos sites dos mercados. Só que abaixo teremos os botões MISSÃO VISÃO E VALORES um ao lado do outro, botões branquinhos como o abaixo. Clicou em algum dos tres botões vai para uma sessão que vamos montar juntos. 

![image](https://cloud.githubusercontent.com/assets/16900593/24912770/80b2512e-1ea5-11e7-833b-ab7321fde266.png)

- [ ] 3. Fazer a seção compromisso social ser idêntica à seção Compromisso social dos sites dos mercados. Botão doe agora abre nova janela navegador. Botão Saiba Mais vai pra nossa página de compromisso social 

- [ ] 4. Fazer a sessão contato ser idêntica à seção contato dos outros sites. 

- [ ] 5. Seção trabalhe conosco montaremos o layout dela depois eu e tu.

**Comment by ezequielmross** [comment]
TDT: 2hs

**Comment by pauloesteves** [comment]
Já foi matada semana passada.
